import { Recipe } from "@/models/recipe";

const recipeData = [
  {
    name: "Vegetable Tricolour Fried Rice",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "200",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/18.jpg",
    latest: false,
    quantityAvailable: 10,
  },
  {
    name: "Phulka",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "45",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/25.jpg",
    latest: false,
    quantityAvailable: 58,
  },
  {
    name: "Alfredo Pasta",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "185",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/26.jpg",
    latest: true,
    quantityAvailable: 29,
  },
  {
    name: "French Fries",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "90",
    shop: "JUICE MALL",
    pic: "https://www.app.tutorjoes.in/img/food/33.jpg",
    latest: false,
    quantityAvailable: 77,
  },
  {
    name: "Veg Nuggets",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "80",
    shop: "JUICE MALL",
    pic: "https://www.app.tutorjoes.in/img/food/34.jpg",
    latest: true,
    quantityAvailable: 72,
  },
  {
    name: "Cheese Corn Sandwich",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "90",
    shop: "JUICE MALL",
    pic: "https://www.app.tutorjoes.in/img/food/35.jpg",
    latest: false,
    quantityAvailable: 31,
  },
  {
    name: "Plain",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "40",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/97.jpg",
    latest: false,
    quantityAvailable: 25,
  },
  {
    name: "Paper Roast",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "65",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/98.jpg",
    latest: false,
    quantityAvailable: 41,
  },
  {
    name: "Onion Roast",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "80",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/99.jpg",
    latest: false,
    quantityAvailable: 88,
  },
  {
    name: "Paratha",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "65",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/105.jpg",
    latest: false,
    quantityAvailable: 73,
  },
  {
    name: "Veg Biryani",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "70",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/106.jpg",
    latest: false,
    quantityAvailable: 94,
  },
  {
    name: "Tomato Rice",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "60",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/107.jpg",
    latest: false,
    quantityAvailable: 2,
  },
  {
    name: "Sambar Rice",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "60",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/108.jpg",
    latest: false,
    quantityAvailable: 60,
  },
  {
    name: "Curd Rice",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "60",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/109.jpg",
    latest: false,
    quantityAvailable: 88,
  },
  {
    name: "Meals",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "160",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/110.jpg",
    latest: false,
    quantityAvailable: 50,
  },
  {
    name: "Mini Meals",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "160",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/111.jpg",
    latest: false,
    quantityAvailable: 61,
  },
  {
    name: "Chapati",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "69",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/112.jpg",
    latest: false,
    quantityAvailable: 91,
  },
  {
    name: "Curd Vadai",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "38",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/113.jpg",
    latest: false,
    quantityAvailable: 74,
  },
  {
    name: "Parotta With Kuruma",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "69",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/114.jpg",
    latest: false,
    quantityAvailable: 94,
  },
  {
    name: "Paneer Butter",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "169",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/115.jpg",
    latest: false,
    quantityAvailable: 10,
  },
  {
    name: "Onion Uthappam",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "75",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/117.jpg",
    latest: true,
    quantityAvailable: 92,
  },
  {
    name: "Vegetable Soup",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "123",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/120.jpg",
    latest: false,
    quantityAvailable: 22,
  },
  {
    name: "Cutlet",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "33",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/121.jpg",
    latest: false,
    quantityAvailable: 31,
  },
  {
    name: "Paper Roast Dosa",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "65",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/124.jpg",
    latest: false,
    quantityAvailable: 17,
  },
  {
    name: "Filter Coffee",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "38",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/125.jpg",
    latest: false,
    quantityAvailable: 93,
  },
  {
    name: "Veg Fried Rice",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "139",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/126.jpg",
    latest: false,
    quantityAvailable: 12,
  },
  {
    name: "Mushroom Fried Rice",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "142",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/127.jpg",
    latest: false,
    quantityAvailable: 19,
  },
  {
    name: "Mushroom Pulao",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "133",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/128.jpg",
    latest: false,
    quantityAvailable: 85,
  },
  {
    name: "Veg Seekh Kebab",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "230",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/130.jpg",
    latest: true,
    quantityAvailable: 13,
  },
  {
    name: "Veg Platter",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "500",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/147.jpg",
    latest: false,
    quantityAvailable: 44,
  },
  {
    name: "Paneer Tikka Masala",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "270",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/148.jpg",
    latest: false,
    quantityAvailable: 68,
  },
  {
    name: "Paneer Butter Masala",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "250",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/149.jpg",
    latest: false,
    quantityAvailable: 59,
  },
  {
    name: "Dal Tadka",
    categoryId: "686aac704399bb9c93cc6fb5",
    amount: "200",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/150.jpg",
    latest: false,
    quantityAvailable: 75,
  },
  {
    name: "Milk Halwa",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "77",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/67.jpg",
    latest: false,
    quantityAvailable: 57,
  },
  {
    name: "Badam Halwa",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "120",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/68.jpg",
    latest: true,
    quantityAvailable: 91,
  },
  {
    name: "Badam Sonpapdi",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "35",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/69.jpg",
    latest: false,
    quantityAvailable: 4,
  },
  {
    name: "Laddu",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "30",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/70.jpg",
    latest: false,
    quantityAvailable: 17,
  },
  {
    name: "Malai Doda",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "35",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/71.jpg",
    latest: false,
    quantityAvailable: 21,
  },
  {
    name: "Raskadam",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "25",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/72.jpg",
    latest: false,
    quantityAvailable: 51,
  },
  {
    name: "Mundri Cake",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "30",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/73.jpg",
    latest: false,
    quantityAvailable: 13,
  },
  {
    name: "Mysore Pak",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "35",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/74.jpg",
    latest: false,
    quantityAvailable: 41,
  },
  {
    name: "Pista Roll",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "25",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/75.jpg",
    latest: false,
    quantityAvailable: 85,
  },
  {
    name: "Rasgulla",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "30",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/76.jpg",
    latest: false,
    quantityAvailable: 4,
  },
  {
    name: "Jamoon",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "30",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/77.jpg",
    latest: false,
    quantityAvailable: 70,
  },
  {
    name: "Badusa",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "30",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/78.jpg",
    latest: true,
    quantityAvailable: 63,
  },
  {
    name: "Malaigulla",
    categoryId: "686aac704399bb9c93cc6fb6",
    amount: "30",
    shop: "Shri Gupta Sweets",
    pic: "https://www.app.tutorjoes.in/img/food/79.jpg",
    latest: false,
    quantityAvailable: 35,
  },
  {
    name: "Sweet corn Chicken Soup",
    categoryId: "686aac704399bb9c93cc6fb7",
    amount: "109",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/13.jpg",
    latest: true,
    quantityAvailable: 71,
  },
  {
    name: "Chicken Manchow",
    categoryId: "686aac704399bb9c93cc6fb7",
    amount: "109",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/14.jpg",
    latest: false,
    quantityAvailable: 99,
  },
  {
    name: "Tomato Soup",
    categoryId: "686aac704399bb9c93cc6fb7",
    amount: "60",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/118.jpg",
    latest: false,
    quantityAvailable: 16,
  },
  {
    name: "Vegetable",
    categoryId: "686aac704399bb9c93cc6fb7",
    amount: "60",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/119.jpg",
    latest: true,
    quantityAvailable: 83,
  },
  {
    name: "Chicken Hot and Sour Soup",
    categoryId: "686aac704399bb9c93cc6fb7",
    amount: "150",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/136.jpg",
    latest: true,
    quantityAvailable: 7,
  },
  {
    name: "Cream of Chicken Soup",
    categoryId: "686aac704399bb9c93cc6fb7",
    amount: "150",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/137.jpg",
    latest: false,
    quantityAvailable: 72,
  },
  {
    name: "Chicken Lemon Coriander",
    categoryId: "686aac704399bb9c93cc6fb7",
    amount: "150",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/138.jpg",
    latest: false,
    quantityAvailable: 46,
  },
  {
    name: '7" Veg Extravaganza Pizza',
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "219",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/12.jpg",
    latest: false,
    quantityAvailable: 27,
  },
  {
    name: "Momo Mia Meal",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "299",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/80.jpg",
    latest: false,
    quantityAvailable: 85,
  },
  {
    name: "Momo Mia",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "349",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/81.jpg",
    latest: false,
    quantityAvailable: 35,
  },
  {
    name: "Momo Mia Choco Sundae Meal",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "319",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/82.jpg",
    latest: false,
    quantityAvailable: 98,
  },
  {
    name: "Baked Cheesy Momo Meal",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "229",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/83.jpg",
    latest: false,
    quantityAvailable: 8,
  },
  {
    name: "Baked Cheesy Momo Meal",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "249",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/84.jpg",
    latest: false,
    quantityAvailable: 1,
  },
  {
    name: "Margherita",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "149",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/85.jpg",
    latest: true,
    quantityAvailable: 78,
  },
  {
    name: "Corn & Cheese",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "179",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/86.jpg",
    latest: false,
    quantityAvailable: 45,
  },
  {
    name: "Veggie Feast",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "229",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/87.jpg",
    latest: false,
    quantityAvailable: 62,
  },
  {
    name: "Tandoori Paneer",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "230",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/88.jpg",
    latest: false,
    quantityAvailable: 31,
  },
  {
    name: "Farmers Pick",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "299",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/89.jpg",
    latest: false,
    quantityAvailable: 74,
  },
  {
    name: "Veggie Supreme",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "399",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/90.jpg",
    latest: false,
    quantityAvailable: 62,
  },
  {
    name: "Chicken Sausage",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "299",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/91.jpg",
    latest: true,
    quantityAvailable: 22,
  },
  {
    name: "Chicken Tikka",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "369",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/92.jpg",
    latest: false,
    quantityAvailable: 33,
  },
  {
    name: "Triple Chicken Feast",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "499",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/93.jpg",
    latest: false,
    quantityAvailable: 69,
  },
  {
    name: "Cheesy Comfort",
    categoryId: "686aac704399bb9c93cc6fb8",
    amount: "219",
    shop: "Pizza Hut",
    pic: "https://www.app.tutorjoes.in/img/food/94.jpg",
    latest: false,
    quantityAvailable: 97,
  },
  {
    name: "Grill Chicken Pepper Fry",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "270",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/1.jpg",
    latest: false,
    quantityAvailable: 1,
  },
  {
    name: "Mutton Biryani",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "350",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/2.jpg",
    latest: false,
    quantityAvailable: 1,
  },
  {
    name: "Chicken 65 Biryani",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "280.5",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/3.jpg",
    latest: false,
    quantityAvailable: 80,
  },
  {
    name: "Plain Biryani",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "180",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/4.jpg",
    latest: false,
    quantityAvailable: 8,
  },
  {
    name: "Egg Biryani",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "210",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/5.jpg",
    latest: false,
    quantityAvailable: 51,
  },
  {
    name: "Chicken biriyani",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "270",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/6.jpg",
    latest: false,
    quantityAvailable: 44,
  },
  {
    name: "Chicken Lollipop",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "220",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/7.jpg",
    latest: false,
    quantityAvailable: 13,
  },
  {
    name: "Muttun Pepper Fry",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "280",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/8.jpg",
    latest: false,
    quantityAvailable: 56,
  },
  {
    name: "Chicken 65",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "220",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/9.jpg",
    latest: false,
    quantityAvailable: 68,
  },
  {
    name: "Chicken Pepper Fry",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "220",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/10.jpg",
    latest: false,
    quantityAvailable: 71,
  },
  {
    name: "Grill Chicken",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "245",
    shop: "Salem Rr Briyani",
    pic: "https://www.app.tutorjoes.in/img/food/11.jpg",
    latest: false,
    quantityAvailable: 80,
  },
  {
    name: "Dragon Chicken 1",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "220",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/15.jpg",
    latest: false,
    quantityAvailable: 23,
  },
  {
    name: "Drums of Heaven",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "255",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/16.jpg",
    latest: false,
    quantityAvailable: 36,
  },
  {
    name: "Punjabi Chicken Gravy",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "255",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/17.jpg",
    latest: true,
    quantityAvailable: 92,
  },
  {
    name: "Egg Fried Rice",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "190",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/19.jpg",
    latest: false,
    quantityAvailable: 16,
  },
  {
    name: "Hyderabad Chicken Dry",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "235",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/20.jpg",
    latest: false,
    quantityAvailable: 66,
  },
  {
    name: "Fish 65",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "260",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/21.jpg",
    latest: false,
    quantityAvailable: 21,
  },
  {
    name: "Mutton Fry",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "330",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/22.jpg",
    latest: false,
    quantityAvailable: 4,
  },
  {
    name: "Roasted Tandoori Chicken",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "255",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/23.jpg",
    latest: false,
    quantityAvailable: 11,
  },
  {
    name: "Tandoori Chicken",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "240",
    shop: "LAKSHMI FOOD",
    pic: "https://www.app.tutorjoes.in/img/food/24.jpg",
    latest: false,
    quantityAvailable: 97,
  },
  {
    name: "Egg Poriyal",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "65",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/95.jpg",
    latest: false,
    quantityAvailable: 27,
  },
  {
    name: "Kalakki",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "23",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/96.jpg",
    latest: false,
    quantityAvailable: 24,
  },
  {
    name: "Egg Parotta",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "55",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/100.jpg",
    latest: false,
    quantityAvailable: 33,
  },
  {
    name: "Plain Omelette",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "25",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/101.jpg",
    latest: false,
    quantityAvailable: 77,
  },
  {
    name: "Kadai Fry",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "150",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/102.jpg",
    latest: true,
    quantityAvailable: 75,
  },
  {
    name: "Egg Veechu",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "65",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/103.jpg",
    latest: false,
    quantityAvailable: 54,
  },
  {
    name: "Egg Roast",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "65",
    shop: "Pugal Ragu Bawa Tiffen Center",
    pic: "https://www.app.tutorjoes.in/img/food/104.jpg",
    latest: true,
    quantityAvailable: 9,
  },
  {
    name: "Gobi Manchurian",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "133",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/116.jpg",
    latest: false,
    quantityAvailable: 34,
  },
  {
    name: "Paneer 65",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "165",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/122.jpg",
    latest: false,
    quantityAvailable: 51,
  },
  {
    name: "Baby Corn 65",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "133",
    shop: "Sri Saivihar",
    pic: "https://www.app.tutorjoes.in/img/food/123.jpg",
    latest: false,
    quantityAvailable: 83,
  },
  {
    name: "Grill Chicken Half",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "180",
    shop: "Absolute Grill Restaurant",
    pic: "https://www.app.tutorjoes.in/img/food/129.jpg",
    latest: false,
    quantityAvailable: 26,
  },
  {
    name: "Chicken Malai Tikka",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "300",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/131.jpg",
    latest: false,
    quantityAvailable: 6,
  },
  {
    name: "Chicken Seekh Kebab",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "180",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/132.jpg",
    latest: false,
    quantityAvailable: 74,
  },
  {
    name: "Spicy Chicken Afghani",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "350",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/133.jpg",
    latest: false,
    quantityAvailable: 75,
  },
  {
    name: "Chicken Cheese Kebab",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "300",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/134.jpg",
    latest: false,
    quantityAvailable: 96,
  },
  {
    name: "Chicken Manchow Soup",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "150",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/135.jpg",
    latest: false,
    quantityAvailable: 14,
  },
  {
    name: "Chilli Paneer Dry",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "250",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/139.jpg",
    latest: false,
    quantityAvailable: 70,
  },
  {
    name: "Dragon Paneer",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "250",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/140.jpg",
    latest: false,
    quantityAvailable: 1,
  },
  {
    name: "Chilli Chicken Dry",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "250",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/141.jpg",
    latest: false,
    quantityAvailable: 19,
  },
  {
    name: "Chilli Chicken Gravy",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "260",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/142.jpg",
    latest: false,
    quantityAvailable: 68,
  },
  {
    name: "Chicken Manchurian Dry",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "250",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/143.jpg",
    latest: true,
    quantityAvailable: 70,
  },
  {
    name: "Chicken Manchurian Gravy",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "260",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/144.jpg",
    latest: false,
    quantityAvailable: 39,
  },
  {
    name: "Dragon Chicken",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "250",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/145.jpg",
    latest: false,
    quantityAvailable: 44,
  },
  {
    name: "Chicken Lollipop TW",
    categoryId: "686aac704399bb9c93cc6fb9",
    amount: "250",
    shop: "Tandoori Wala",
    pic: "https://www.app.tutorjoes.in/img/food/146.jpg",
    latest: false,
    quantityAvailable: 58,
  },
  {
    name: "Carrot Juice",
    categoryId: "686aac704399bb9c93cc6fba",
    amount: "90",
    shop: "JUICE MALL",
    pic: "https://www.app.tutorjoes.in/img/food/27.jpg",
    latest: false,
    quantityAvailable: 5,
  },
  {
    name: "Orange Juice",
    categoryId: "686aac704399bb9c93cc6fba",
    amount: "70",
    shop: "JUICE MALL",
    pic: "https://www.app.tutorjoes.in/img/food/28.jpg",
    latest: false,
    quantityAvailable: 56,
  },
  {
    name: "Lemon Mint Juice",
    categoryId: "686aac704399bb9c93cc6fba",
    amount: "80",
    shop: "JUICE MALL",
    pic: "https://www.app.tutorjoes.in/img/food/29.jpg",
    latest: false,
    quantityAvailable: 32,
  },
  {
    name: "Pineapple Lime Juice",
    categoryId: "686aac704399bb9c93cc6fba",
    amount: "80",
    shop: "JUICE MALL",
    pic: "https://www.app.tutorjoes.in/img/food/30.jpg",
    latest: false,
    quantityAvailable: 10,
  },
  {
    name: "Watermelon Lime Juice",
    categoryId: "686aac704399bb9c93cc6fba",
    amount: "80",
    shop: "JUICE MALL",
    pic: "https://www.app.tutorjoes.in/img/food/31.jpg",
    latest: false,
    quantityAvailable: 56,
  },
  {
    name: "Blue Mojito",
    categoryId: "686aac704399bb9c93cc6fba",
    amount: "100",
    shop: "JUICE MALL",
    pic: "https://www.app.tutorjoes.in/img/food/32.jpg",
    latest: false,
    quantityAvailable: 21,
  },
  {
    name: "Sweet Cream Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "69",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/36.jpg",
    latest: false,
    quantityAvailable: 82,
  },
  {
    name: "Butterscotch Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "99",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/37.jpg",
    latest: false,
    quantityAvailable: 98,
  },
  {
    name: "Cookie Dough Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "99",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/38.jpg",
    latest: false,
    quantityAvailable: 67,
  },
  {
    name: "Cotton Candy Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "99",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/39.jpg",
    latest: true,
    quantityAvailable: 34,
  },
  {
    name: "Mint Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "105",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/40.jpg",
    latest: false,
    quantityAvailable: 92,
  },
  {
    name: "Blackcurrant Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "99",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/41.jpg",
    latest: false,
    quantityAvailable: 80,
  },
  {
    name: "Jackfruit Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "99",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/42.jpg",
    latest: false,
    quantityAvailable: 33,
  },
  {
    name: "Raspberry Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "99",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/43.jpg",
    latest: false,
    quantityAvailable: 83,
  },
  {
    name: "Mango Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "99",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/44.jpg",
    latest: false,
    quantityAvailable: 97,
  },
  {
    name: "Tender Coconut Scoop",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "99",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/45.jpg",
    latest: false,
    quantityAvailable: 29,
  },
  {
    name: "Cookie Dough Milk Shake",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "159",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/46.jpg",
    latest: false,
    quantityAvailable: 9,
  },
  {
    name: "Butterscotch Milk Shake",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "159",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/47.jpg",
    latest: false,
    quantityAvailable: 3,
  },
  {
    name: "Mango Milk Shake",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "159",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/48.jpg",
    latest: false,
    quantityAvailable: 21,
  },
  {
    name: "Litchi Madness",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "219",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/49.jpg",
    latest: false,
    quantityAvailable: 29,
  },
  {
    name: "Kulfi Sundae",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "179",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/50.jpg",
    latest: false,
    quantityAvailable: 95,
  },
  {
    name: "Swiss Choco Brownie",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "169",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/51.jpg",
    latest: true,
    quantityAvailable: 42,
  },
  {
    name: "Fruit Paradise",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "209",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/52.jpg",
    latest: true,
    quantityAvailable: 47,
  },
  {
    name: "Strawberry Fruit Cream",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "169",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/53.jpg",
    latest: false,
    quantityAvailable: 43,
  },
  {
    name: "Fig & Honey Dry Fruit Cream",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "179",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/54.jpg",
    latest: false,
    quantityAvailable: 9,
  },
  {
    name: "Vanilla Choco Kelloggs",
    categoryId: "686aac704399bb9c93cc6fbb",
    amount: "149",
    shop: "Cream & Fudge",
    pic: "https://www.app.tutorjoes.in/img/food/55.jpg",
    latest: false,
    quantityAvailable: 76,
  },
  {
    name: "Sponge Cake",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "155",
    shop: "Henry & Wolsey",
    pic: "https://www.app.tutorjoes.in/img/food/56.jpg",
    latest: false,
    quantityAvailable: 75,
  },
  {
    name: "Fruit Cake",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "173",
    shop: "Henry & Wolsey",
    pic: "https://www.app.tutorjoes.in/img/food/57.jpg",
    latest: false,
    quantityAvailable: 80,
  },
  {
    name: "Jam Roll Cake",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "101",
    shop: "Henry & Wolsey",
    pic: "https://www.app.tutorjoes.in/img/food/58.jpg",
    latest: false,
    quantityAvailable: 47,
  },
  {
    name: "Red Velvet Cup Cake",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "96",
    shop: "Henry & Wolsey",
    pic: "https://www.app.tutorjoes.in/img/food/59.jpg",
    latest: false,
    quantityAvailable: 95,
  },
  {
    name: "Fresh Cream Black Forest",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "555",
    shop: "Shris Cake Zone",
    pic: "https://www.app.tutorjoes.in/img/food/60.jpg",
    latest: false,
    quantityAvailable: 12,
  },
  {
    name: "Butterscotch",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "555",
    shop: "Shris Cake Zone",
    pic: "https://www.app.tutorjoes.in/img/food/61.jpg",
    latest: false,
    quantityAvailable: 74,
  },
  {
    name: "Red Velvet",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "715",
    shop: "Shris Cake Zone",
    pic: "https://www.app.tutorjoes.in/img/food/62.jpg",
    latest: false,
    quantityAvailable: 25,
  },
  {
    name: "Red Velvet Pastry",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "157",
    shop: "Shris Cake Zone",
    pic: "https://www.app.tutorjoes.in/img/food/63.jpg",
    latest: false,
    quantityAvailable: 22,
  },
  {
    name: "Classic Walnut Brownie",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "157",
    shop: "Shris Cake Zone",
    pic: "https://www.app.tutorjoes.in/img/food/64.jpg",
    latest: false,
    quantityAvailable: 87,
  },
  {
    name: "Apple Pie",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "189",
    shop: "Shris Cake Zone",
    pic: "https://www.app.tutorjoes.in/img/food/65.jpg",
    latest: true,
    quantityAvailable: 15,
  },
  {
    name: "Kitkat Cake",
    categoryId: "686aac704399bb9c93cc6fbc",
    amount: "145",
    shop: "Shris Cake Zone",
    pic: "https://www.app.tutorjoes.in/img/food/66.jpg",
    latest: false,
    quantityAvailable: 29,
  },
];

async function createRecipes() {
  try {
    const newRecipeData = await Recipe.find();
    if (newRecipeData.length <= 0) {
      Recipe.insertMany(recipeData);
      return console.log("Successfully Recipe created");
    }
    return console.log("Already Recipe created");
  } catch (error) {
    return console.log(error);
  }
}

export { createRecipes };
